ConcertGo/Controllers/ArtistsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ConcertGo.Models;
using ConcertGo.ViewModels;

namespace ConcertGo.Controllers
{
    public class ArtistsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Artists
        public async Task<ActionResult> Index()
        {
            return View(await db.Artists.ToListAsync());
        }

        // GET: Artists/Details/5
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist artist = await db.Artists.FindAsync(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            return View(artist);
        }

        // GET: Artists/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Artists/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateArtistViewModel artist)
        {
            if (!ModelState.IsValid) return View(artist);

            using (var context = new ApplicationDbContext())
            {
                context.Artists.Add(new Artist
                {
                    Id = Guid.NewGuid(),
                    Name = artist.ArtistName,
                    Concerts = new List<Concert>
                    {
                        new Concert
                        {
                            Id = Guid.NewGuid(),
                            Name = artist.ConcertName,
                            Media = new List<Media>()
                        }
                    }
                });

                await context.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

        // GET: Artists/Edit/5
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist artist = await db.Artists.FindAsync(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            return View(artist);
        }

        // POST: Artists/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name")] Artist artist)
        {
            if (ModelState.IsValid)
            {
                db.Entry(artist).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(artist);
        }

        // GET: Artists/Delete/5
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist artist = await db.Artists.FindAsync(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            return View(artist);
        }

        // POST: Artists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            Artist artist = await db.Artists.FindAsync(id);
            db.Artists.Remove(artist);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ConcertGo/Controllers/ConcertController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ConcertGo.Models;
using ConcertGo.ViewModels;

namespace ConcertGo.Controllers
{
    public class ConcertController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Concert
        public async Task<ActionResult> Index()
        {
            return View(await db.Concerts.ToListAsync());
        }

        // GET: Concert/Details/5
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var concert = await db.Concerts.Include(c => c.Media.Select(m => m.Files)).FirstAsync(x=> x.Id == id).ContinueWith(x => // todo will return null, fix it.
            {
                return new ConcertDetailViewModel
                {
                    Artists = x.Result.Artists.Select(y => new ArtistViewModel
                    {
                        Name = y.Name
                    }),
                    Name = x.Result.Name,
                    Id = x.Result.Id,
                    Media = x.Result.Media.Select(y => new MediaViewModel
                    {
                        Comment = y.Comment,
                        Files = y.Files.Select(z => new FileViewModel
                        {
                            Id = z.Id,
                            Url = z.Url
                        })
                    })
                };
            });

            if (concert == null)
            {
                return HttpNotFound();
            }
            return View(concert);
        }

        // GET: Concert/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Concert/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name")] Concert concert)
        {
            if (ModelState.IsValid)
            {
                concert.Id = Guid.NewGuid();
                db.Concerts.Add(concert);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(concert);
        }

        // GET: Concert/Edit/5
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Concert concert = await db.Concerts.FindAsync(id);
            if (concert == null)
            {
                return HttpNotFound();
            }
            return View(concert);
        }

        // POST: Concert/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name")] Concert concert)
        {
            if (ModelState.IsValid)
            {
                db.Entry(concert).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(concert);
        }

        // GET: Concert/Delete/5
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Concert concert = await db.Concerts.FindAsync(id);
            if (concert == null)
            {
                return HttpNotFound();
            }
            return View(concert);
        }

        // POST: Concert/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            Concert concert = await db.Concerts.FindAsync(id);
            db.Concerts.Remove(concert);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ConcertGo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/bundles/css")
</head>
<body>

<div class="uk-child-width-expand@s uk-text-left" uk-grid>
    <div class="uk-width-1-6@m uk-margin-small">
        <!-- MENU -->
        <div class="uk-card uk-card-default uk-card-body" uk-sticky="show-on-up: true; animation: uk-animation-slide-top; bottom: #bottom">
            <ul class="uk-nav-default uk-nav-parent-icon" uk-nav>
                <li class="uk-active">@Html.ActionLink("Home", "Index", "Home")</li>
                <li class="uk-parent">
                    <a href="#">Artists</a>
                    <ul class="uk-nav-sub">
                        <li><a href="#">Popular Artist 1</a></li>
                        <li><a href="#">Popular Artist 2</a></li>
                        <li class="uk-text-bold">@Html.ActionLink("View All Artists", "Index", "Artists")</li>
                    </ul>
                </li>
                <li class="uk-parent">
                    <a href="#">Concerts</a>
                    <ul class="uk-nav-sub">
                        <li><a href="#">Popular Concert 1</a></li>
                        <li><a href="#">Popular Concert 2</a></li>
                        <li class="uk-text-bold">@Html.ActionLink("View All Concerts", "Index", "Concert")</li>
                    </ul>
                </li>
                <li class="uk-nav-header">Footage</li>
                <li><a href="#"><span class="uk-margin-small-right" uk-icon="icon: plus"></span> Upload Footage</a></li>
                <li><a href="#"><span class="uk-margin-small-right" uk-icon="icon: image"></span> Manage Footage</a></li>
                <li class="uk-nav-divider"></li>
                @Html.Partial("_LoginPartial")
            </ul>
        </div>
    </div>
    
    <!-- BODY -->
    <div>
        <header class="uk-card uk-card-body uk-background-primary uk-light" style="margin-bottom: 40px;">
            <h1 class="uk-h3">ConcertGo</h1>
        </header>

        <div class="uk-width-auto@m">@RenderBody()</div>
    </div>
</div>

@Scripts.Render("~/bundles/js")
@RenderSection("scripts", false)
</body>
</html>

ConcertGo/Views/Shared/_LoginPanelPartial.cshtml
@model ConcertGo.Models.LoginViewModel

<h2>Login</h2>

@using (Html.BeginForm("Login", "Account", new {ViewBag.ReturnUrl}, FormMethod.Post, new {@class = "uk-fieldset", role = "form", id="userLoginPanel"}))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new {@class = "uk-text-danger" })

    <div class="uk-margin">
        @Html.LabelFor(m => m.Email, new { @class = "uk-form-label" })
        @Html.TextBoxFor(m => m.Email, new {@class = "uk-input"})
        @Html.ValidationMessageFor(m => m.Email, "", new {@class = "uk-text-danger"})
    </div>

    <div class="uk-margin">
        @Html.LabelFor(m => m.Password, new { @class = "uk-form-label" })
        @Html.PasswordFor(m => m.Password, new {@class = "uk-input"})
        @Html.ValidationMessageFor(m => m.Password, "", new {@class = "uk-text-danger"})
    </div>

    <div class="">
        @Html.CheckBoxFor(m => m.RememberMe, new {@class = "uk-checkbox"})
        @Html.LabelFor(m => m.RememberMe, new {@class = "uk-form-label"})
    </div>
}

@* Enable this once you have account confirmation enabled for password reset functionality
<p>
    @Html.ActionLink("Forgot your password?", "ForgotPassword")
</p>
<div class="col-md-4">
    <section id="socialLoginForm">
        @Html.Partial("_ExternalLoginsListPartial", new ExternalLoginListViewModel { ReturnUrl = ViewBag.ReturnUrl })
    </section>
</div>*@

ConcertGo/Views/Shared/_RegisterPanelPartial.cshtml
@model ConcertGo.Models.RegisterViewModel

<h2>Register</h2>

@using (Html.BeginForm("Register", "Account", FormMethod.Post, new { @class = "uk-fieldset", role = "form", id = "userRegisterPanel" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary("", new { @class = "uk-text-danger" })

    <div class="uk-margin">
        @Html.LabelFor(m => m.Email, new { @class = "uk-form-label" })
        @Html.TextBoxFor(m => m.Email, new { @class = "uk-input" })
    </div>

    <div class="uk-margin">
        @Html.LabelFor(m => m.Password, new { @class = "uk-form-label" })
        @Html.PasswordFor(m => m.Password, new { @class = "uk-input" })
    </div>

    <div class="uk-margin" style="margin-bottom: 0">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "uk-form-label" })
        @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "uk-input" })
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}